--ID, NAME,CONTENT,PRICE,COMPANY,IMG
CREATE TABLE PRODUCT(
	ID VARCHAR2(200),
	NAME VARCHAR2(200),
	CONTENT VARCHAR2(200),
	PRICE VARCHAR2(200),
	COMPANY VARCHAR2(200),
	IMG VARCHAR2(200)
)

SELECT * FROM PRODUCT ORDER BY PRICE ASC

SELECT NAME, CONTENT, PRICE FROM PRODUCT ORDER BY COMPANY ASC

SELECT NAME, PRICE FROM PRODUCT WHERE ID='100'

SELECT NAME, COMPANY FROM PRODUCT WHERE PRICE='5000'

SELECT NAME, IMG FROM PRODUCT WHERE ID='100' AND PRICE='1000'

SELECT COMPANY, NAME FROM PRODUCT WHERE COMPANY='c100'

SELECT NAME, PRICE FROM PRODUCT WHERE COMPANY='c100' OR COMPANY='c200'

UPDATE PRODUCT SET CONTENT='품절' WHERE PRICE ='5000'

UPDATE PRODUCT SET IMG='O.PNG', PRICE='10000' WHERE ID='100' OR ID='102'

UPDATE PRODUCT SET COMPANY = 'APPLE',NAME='APPLESHOES' WHERE ID='101'

DELETE FROM PRODUCT WHERE NAME='shoes1' OR ID='107'

DELETE FROM PRODUCT WHERE COMPANY ='c100'

DELETE FROM PRODUCT 

DROP TABLE PRODUCT 