CREATE TABLE "HR".PRODUCT3
(	"ID" VARCHAR2(200),
"NAME" VARCHAR2(200),
"CONTENT" VARCHAR2(200),
"PRICE" NUMBER(38,0),
"COMPANY" VARCHAR2(200),
"IMG" VARCHAR2(200)
)

SELECT * FROM "HR".PRODUCT3
ORDER BY PRICE DESC

SELECT NAME,CONTENT,PRICE FROM "HR".PRODUCT3
ORDER BY COMPANY 

SELECT DISTINCT COMPANY FROM "HR".PRODUCT3

SELECT NAME, PRICE*5 AS PRICE5 FROM "HR".PRODUCT3 

SELECT NAME, COMPANY FROM "HR".PRODUCT3
WHERE PRICE=5000

SELECT NAME, PRICE, COMPANY FROM "HR".PRODUCT3
WHERE PRICE BETWEEN 3000 AND 6000

SELECT NAME, COMPANY FROM "HR".PRODUCT3
WHERE COMPANY != 'c100'

SELECT NAME, PRICE FROM "HR".PRODUCT3
WHERE COMPANY = 'c100' OR COMPANY ='c200'

SELECT * FROM "HR".PRODUCT3
WHERE NAME LIKE '%4'

SELECT * FROM "HR".PRODUCT3
WHERE CONTENT LIKE '%food%'

UPDATE "HR".PRODUCT3
SET CONTENT = '품절'
WHERE PRICE =5000

SELECT * FROM "HR".PRODUCT3

UPDATE "HR".PRODUCT3
SET IMG='O.PNG', PRICE = 10000
WHERE ID =100 OR ID=102

SELECT * FROM "HR".PRODUCT3

DELETE FROM "HR".PRODUCT3
WHERE COMPANY ='c100'

DELETE FROM "HR".PRODUCT3
